export const siteConfig = {
  name: "Visnec Nexus",
  shortName: "VNX",
  description: "Visnec Nexus (VNX) - A comprehensive ecosystem of tools, platforms, directories, and marketplaces for global innovators and travelers.",
  url: "https://visnec.ai",
  ogImage: "https://visnec.ai/og-image.png",
  links: {
    twitter: "https://twitter.com/visnec",
    github: "https://github.com/visnec",
    visnec: "https://visnec.com",
  },
  creator: "Visnec Global",
  keywords: [
    "Visnec Nexus",
    "VNX",
    "eSIM",
    "global connectivity",
    "digital tools",
    "platforms",
    "marketplace",
    "innovation",
  ],
};

export const pillars = [
  {
    id: "tools",
    name: "Tools",
    description: "Powerful utilities for productivity and innovation",
    href: "/tools",
    icon: "Wrench",
  },
  {
    id: "platforms",
    name: "Platforms",
    description: "Integrated solutions for various needs",
    href: "/platforms",
    icon: "Layers",
  },
  {
    id: "directories",
    name: "Directories",
    description: "Curated listings and resources",
    href: "/directories",
    icon: "FolderTree",
  },
  {
    id: "resources",
    name: "Resources",
    description: "Knowledge base and learning materials",
    href: "/resources",
    icon: "BookOpen",
  },
  {
    id: "community",
    name: "Community",
    description: "Connect with like-minded individuals",
    href: "/community",
    icon: "Users",
  },
  {
    id: "marketplace",
    name: "Marketplace",
    description: "Buy and sell products and services",
    href: "/marketplace",
    icon: "ShoppingCart",
  },
  {
    id: "insights",
    name: "Insights",
    description: "Data-driven analysis and reports",
    href: "/insights",
    icon: "BarChart",
  },
  {
    id: "experiences",
    name: "Experiences",
    description: "Unique journeys and adventures",
    href: "/experiences",
    icon: "Compass",
  },
  {
    id: "trends",
    name: "Trends",
    description: "Latest developments and innovations",
    href: "/trends",
    icon: "TrendingUp",
  },
  {
    id: "ventures",
    name: "Ventures",
    description: "Investment and startup opportunities",
    href: "/ventures",
    icon: "Rocket",
  },
  {
    id: "e-services",
    name: "E-Services",
    description: "Digital services for modern needs",
    href: "/e-services",
    icon: "Globe",
  },
];

