// Mock Data for NexusTracker Demo

import { Project, Task, User, Activity, TimeEntry } from './types';

export const mockUsers: User[] = [
  {
    id: '1',
    name: 'Sarah Johnson',
    email: 'sarah@visnec.ai',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
    role: 'admin',
  },
  {
    id: '2',
    name: 'Michael Chen',
    email: 'michael@visnec.ai',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Michael',
    role: 'manager',
  },
  {
    id: '3',
    name: 'Emily Rodriguez',
    email: 'emily@visnec.ai',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emily',
    role: 'member',
  },
  {
    id: '4',
    name: 'David Kim',
    email: 'david@visnec.ai',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=David',
    role: 'member',
  },
];

export const mockProjects: Project[] = [
  {
    id: '1',
    name: 'VNX Platform Redesign',
    description: 'Complete redesign of the VNX platform with modern UI/UX',
    status: 'active',
    startDate: '2025-01-01',
    endDate: '2025-06-30',
    progress: 65,
    color: '#6366f1',
    owner: mockUsers[0],
    members: [mockUsers[0], mockUsers[1], mockUsers[2]],
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-10-17T00:00:00Z',
  },
  {
    id: '2',
    name: 'NexusTracker Development',
    description: 'Build comprehensive project management platform',
    status: 'active',
    startDate: '2025-02-15',
    endDate: '2025-12-31',
    progress: 45,
    color: '#8b5cf6',
    owner: mockUsers[1],
    members: [mockUsers[1], mockUsers[2], mockUsers[3]],
    createdAt: '2025-02-15T00:00:00Z',
    updatedAt: '2025-10-17T00:00:00Z',
  },
  {
    id: '3',
    name: 'Marketing Campaign Q4',
    description: 'Launch new marketing initiatives for Q4 2025',
    status: 'planning',
    startDate: '2025-10-01',
    endDate: '2025-12-31',
    progress: 15,
    color: '#ec4899',
    owner: mockUsers[0],
    members: [mockUsers[0], mockUsers[3]],
    createdAt: '2025-09-01T00:00:00Z',
    updatedAt: '2025-10-17T00:00:00Z',
  },
];

export const mockTasks: Task[] = [
  {
    id: '1',
    title: 'Design new dashboard layout',
    description: 'Create mockups for the new dashboard with improved UX',
    projectId: '1',
    status: 'in-progress',
    priority: 'high',
    assignee: mockUsers[2],
    reporter: mockUsers[0],
    dueDate: '2025-10-25',
    estimatedHours: 16,
    actualHours: 10,
    tags: ['design', 'ui/ux'],
    subtasks: [
      { id: 's1', title: 'Create wireframes', completed: true, createdAt: '2025-10-10T00:00:00Z' },
      { id: 's2', title: 'Design high-fidelity mockups', completed: false, createdAt: '2025-10-12T00:00:00Z' },
    ],
    attachments: [],
    comments: [
      {
        id: 'c1',
        content: 'Looking great so far! Let\'s add more interactive elements.',
        author: mockUsers[0],
        createdAt: '2025-10-15T10:30:00Z',
      },
    ],
    dependencies: [],
    createdAt: '2025-10-10T00:00:00Z',
    updatedAt: '2025-10-17T00:00:00Z',
  },
  {
    id: '2',
    title: 'Implement authentication system',
    description: 'Set up Supabase authentication with role-based access',
    projectId: '1',
    status: 'done',
    priority: 'urgent',
    assignee: mockUsers[1],
    reporter: mockUsers[0],
    dueDate: '2025-10-15',
    estimatedHours: 24,
    actualHours: 28,
    tags: ['backend', 'security'],
    subtasks: [
      { id: 's3', title: 'Set up Supabase project', completed: true, createdAt: '2025-10-01T00:00:00Z' },
      { id: 's4', title: 'Implement login/signup', completed: true, createdAt: '2025-10-03T00:00:00Z' },
      { id: 's5', title: 'Add role-based permissions', completed: true, createdAt: '2025-10-05T00:00:00Z' },
    ],
    attachments: [],
    comments: [],
    dependencies: [],
    createdAt: '2025-10-01T00:00:00Z',
    updatedAt: '2025-10-15T00:00:00Z',
  },
  {
    id: '3',
    title: 'Build Kanban board component',
    description: 'Create drag-and-drop Kanban board for task management',
    projectId: '2',
    status: 'in-progress',
    priority: 'high',
    assignee: mockUsers[3],
    reporter: mockUsers[1],
    dueDate: '2025-10-30',
    estimatedHours: 20,
    actualHours: 12,
    tags: ['frontend', 'react'],
    subtasks: [],
    attachments: [],
    comments: [],
    dependencies: [],
    createdAt: '2025-10-12T00:00:00Z',
    updatedAt: '2025-10-17T00:00:00Z',
  },
  {
    id: '4',
    title: 'Write API documentation',
    description: 'Document all API endpoints with examples',
    projectId: '2',
    status: 'todo',
    priority: 'medium',
    assignee: mockUsers[2],
    reporter: mockUsers[1],
    dueDate: '2025-11-05',
    estimatedHours: 12,
    tags: ['documentation'],
    subtasks: [],
    attachments: [],
    comments: [],
    dependencies: ['2'],
    createdAt: '2025-10-16T00:00:00Z',
    updatedAt: '2025-10-16T00:00:00Z',
  },
  {
    id: '5',
    title: 'Set up CI/CD pipeline',
    description: 'Configure automated testing and deployment',
    projectId: '1',
    status: 'review',
    priority: 'medium',
    assignee: mockUsers[1],
    reporter: mockUsers[0],
    dueDate: '2025-10-20',
    estimatedHours: 8,
    actualHours: 9,
    tags: ['devops', 'automation'],
    subtasks: [],
    attachments: [],
    comments: [],
    dependencies: [],
    createdAt: '2025-10-08T00:00:00Z',
    updatedAt: '2025-10-17T00:00:00Z',
  },
];

export const mockActivities: Activity[] = [
  {
    id: '1',
    type: 'task_completed',
    user: mockUsers[1],
    projectId: '1',
    taskId: '2',
    description: 'completed task "Implement authentication system"',
    timestamp: '2025-10-15T14:30:00Z',
  },
  {
    id: '2',
    type: 'comment_added',
    user: mockUsers[0],
    projectId: '1',
    taskId: '1',
    description: 'commented on "Design new dashboard layout"',
    timestamp: '2025-10-15T10:30:00Z',
  },
  {
    id: '3',
    type: 'task_created',
    user: mockUsers[1],
    projectId: '2',
    taskId: '4',
    description: 'created task "Write API documentation"',
    timestamp: '2025-10-16T09:00:00Z',
  },
  {
    id: '4',
    type: 'member_added',
    user: mockUsers[0],
    projectId: '3',
    description: 'added David Kim to "Marketing Campaign Q4"',
    timestamp: '2025-10-14T11:00:00Z',
  },
  {
    id: '5',
    type: 'task_updated',
    user: mockUsers[3],
    projectId: '2',
    taskId: '3',
    description: 'updated task "Build Kanban board component"',
    timestamp: '2025-10-17T08:15:00Z',
  },
];

export const mockTimeEntries: TimeEntry[] = [
  {
    id: '1',
    taskId: '1',
    userId: '3',
    hours: 4,
    description: 'Worked on wireframes',
    date: '2025-10-15',
    createdAt: '2025-10-15T18:00:00Z',
  },
  {
    id: '2',
    taskId: '2',
    userId: '2',
    hours: 8,
    description: 'Implemented authentication',
    date: '2025-10-14',
    createdAt: '2025-10-14T17:30:00Z',
  },
  {
    id: '3',
    taskId: '3',
    userId: '4',
    hours: 6,
    description: 'Built Kanban board structure',
    date: '2025-10-16',
    createdAt: '2025-10-16T16:45:00Z',
  },
];

